### ISSUE TITLE
Pisces error reporting doesn't give enough information to diagnose through the objects

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#185]
## Describe the bug
As it stands, Pisces isn't including transformation error information in the objects. As it stands, you need to add a print statement to transformer tests to see errors in the command line.

## Expected behavior
API responses should include more information about why something failed.

**Comment by helrond** [comment]
A couple of things need to happen:
- Exception handling needs to move down to inside the for loops in `get_updated` and `get_deleted` in `ArchivesSpaceDataFetcher` and `CartographerDataFetcher`. It may be possible to add this to `send_post_request`.
- the exception handling in `BaseDataFetcher` needs to be removed, because that may result in the function returning `None`.
