### ISSUE TITLE
Do not merge or transform archival_objects from unpublished resources

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/pisces#255]
## Is your feature request related to a problem? Please describe.
Archival objects from unpublished resources should not be merged or transformed. 

## Describe the solution you'd like
Check to see if an archival object belongs to an unpublished resource before sending it to be merged and transformed.

## Describe alternatives you've considered
It would also be possible to handle this on the AS side of things (which we've tentatively broached already with the Head of Processing):
- Unpublish all archival objects belonging to an unpublished resource
- Do not mark new archival objects as published by default
- Require archivists to "Publish all" when new resources have been completely described

This approach would probably require some scripting to bulk unpublish archival objects (and we'd need to have a script ready to do this on an as-needed basis as well) because there does not appear to be a way in the UI to unpublish.

@p-galligan any input?

**Comment by p-galligan** [comment]
I might be missing something here, but wouldn't "Publish All" hit the entire finding aid? Would this cause problems for future workflows where some of the finding aid is public and some isn't?

Do we have any instances where that happens?

Otherwise, it's pretty trivial to change the settings from published by default to unpublished by default. However, I believe that each user has the option to change their own defaults on their account that I can't override with repository preferences. Currently user preferences will always take precedence. However, we could just get around that with messaging from Head of Processing.

The real gotcha here is that Publish All publishes all subrecords as well. Including any unpublished notes or external documents. I know we have legacy unpublished notes for good reason, but I'm not sure if we're still creating them.

Largely though, I think the check to see if an object or collection has an unpublished ancestor is fairly trivial and probably the easiest way to go. There's a "has_unpublished_ancestor" boolean flag on each archival object response. Seems like it'd be pretty easy to to check for.

Ultimately, checking for the unpublished ancestor flag seems the easiest thing to do.

**Comment by helrond** [comment]
Oh wow, I totally blanked on the `has_unpublished_ancestor` field! You're right, that's totally the easiest way to go.
